### PR TITLE
Fix some several easy-to-fix issues.

### PR DESCRIPTION
**Pull request by BarchamMal**
Fix issues:
- #189 
- #219
- #206

### CODE REVIEW

**Review by gniftygnome — COMMENTED** [review]
All four types that can grow on farmland can be run from a single mixin.  See f.e. [the Terraform API mixin](https://github.com/TerraformersMC/Terraform/blob/1.20.3/terraform-dirt-api-v1/src/main/java/com/terraformersmc/terraform/dirt/mixin/MixinPlantingOnFarmland.java) ... another option here would be to just use Terraform API for the rich soil block set (gives easy implementation of grass, path, and podzol too if you like).

**Comment by BarchamMal** [comment]
Thanks for that suggestion! I had no idea mixing could be "batched". And, as a bonus, that also removes 3 other unneeded files, and makes this work with _any_ farmland that uses the c:farmland tag. I just implemented it myself, as it was easier.

**Review by gniftygnome — COMMENTED** [review]
It is maybe a little weird to potentially adjust the behavior of vanilla Farmland and other mods' farmland blocks, albeit probably mostly harmless.  Also, it's better not to cancel (setReturnValue) when you aren't changing the return value, although this is less of an issue when your mixin is at TAIL or RETURN.

**Comment by BarchamMal** [comment]
Hmm, I'm new to mixins and only do simple ones, but, I'm afraid, your comment went over my head.  I'm not sure what you mean by I'm not changing the return value, as it would normally return FALSE if it  was not minecraft:farmland and now returns FALSE if it is not #c:farmland.

**Comment by gniftygnome** [comment]
In addition to canceling when your mixin does change the return value (when the block is not minecraft:farmland but it is in the c:farmland tag), it also cancels in all other cases.  Because of how simple the target method is, this is not a huge deal, but it is better to avoid canceling in the other cases.  For example:

```java
    @Inject(at = @At("TAIL"), method = "canPlantOnTop", cancellable = true)
    private void plantBlocksCanPlantOnTopOfRichSoil(BlockState floor, BlockView world, BlockPos pos, CallbackInfoReturnable<Boolean> cir) {
        if (!cir.getReturnValue() && floor.isIn(TagsRegistry.FARMLAND)) {
            cir.setReturnValue(true);
        }
    }
```

**Comment by gniftygnome** [comment]
> Also, if you think I should just check if it's fd:rich_soil_farmland just not to mess up other mods I'll do that.

It's what I would do, but both of these are more "best practices" things.

**Comment by BarchamMal** [comment]
Okay, now I see. I had thought that injecting into the method auto-canceled it, even when your return was false. I will do what you said. Now I understand why [this](https://github.com/TerraformersMC/Terraform/blob/1.20.3/terraform-dirt-api-v1/src/main/java/com/terraformersmc/terraform/dirt/mixin/MixinPlantingOnFarmland.java) method did it in an if statement.

**Comment by BarchamMal** [comment]
Should I remove the FARMLAND tagkey and the new method I added?

**Comment by gniftygnome** [comment]
> Should I remove the FARMLAND tagkey and the new method I added?

Probably, since they're no longer used.  This does look pretty good to me now.  Bear in mind, though, I am not a maintainer of Farmer's Delight so they might have some other request.

**Pull request merged**
