### PR TITLE
Fix the Create/EMI/Farmers Delight bug

### PR DESCRIPTION
**Pull request by LemmaEOF**
I found the bug! It's the Farmer's Delight Create-compat [chocolate pie filling recipe](https://github.com/newhoryzon/farmers-delight-fabric/blob/master/src/main/resources/data/farmersdelight/recipes/create/filling/chocolate_pie.json) - the fluid tag `c:chocolates` isn't used in Create, it's `c:chocolate` instead, so switching to the proper tag should stop it from getting index out-of-bounds issues!

### CODE REVIEW

**Review by Chikage0o0 — CHANGES_REQUESTED** [review]

**Comment by Chikage0o0** [comment]
Again, this file needs to be modified
`src/main/resources/data/farmersdelight/recipes/create/mixing/pie_crust_from_mixing.json`

`250`->`20250`

**Comment by LemmaEOF** [comment]
Hey, can this get merged? It's a big problem for modpacks still

**Comment by Jamalam360** [comment]
Agreed, it's entirely breaking Create's EMI plugin :(

**Comment by piebaker** [comment]
Agree, also having issues.

**Comment by Ethan23p** [comment]
Still should be merged, please

**Comment by cilcoOf** [comment]
^
agree

**Comment by newtrogicNexus** [comment]
Why is this taking so long to merge?

**Comment by LemmaEOF** [comment]
If this doesn't get merged soon I'm gonna hardfork.

**Review by Zifiv — APPROVED** [review]

**Comment by Zifiv** [comment]
Should fixe: #128 #115.

**Pull request merged**
