### PR TITLE
Fix recipes, loot tables, and other stuff

### PR DESCRIPTION
**Pull request by blu3potato**
- Update recipes for Dumplings and Mutton Wrap
- Remove leftover old recipes for Wheat Dough and Raw Pasta
- Fixes Dyed Canvas Sign recipes, along with missing loot tables for some
- Fixes Basket and Canvas Signs not being mined faster with an axe

Other things:
- Makes Stove, Skillet, and Cooking Pot use tag c:iron_ingots instead of minecraft:iron_ingot
- Updates the bush_crop model to match the new crop model from 1.17
- Adds farmersdelight:tools/knives tag for parity

Some recipes (Cabbage, Pies, Cabinets, etc.) could be put in a group to make the recipe book cleaner, but since it's not in the Forge version I didn't.

### CODE REVIEW

**Comment by Zifiv** [comment]
Hello @blu3potato, thanks for your work and this PR, but some things have been already fixed for next release. You will be marked as contributor for others stuff. Thanks again 😉!

**Comment by blu3potato** [comment]
Hello! May I ask if food values are also updated to parity in the next release? I planned to open another PR for it but if that's the case then I won't. Thank you!

**Comment by blu3potato** [comment]
> Hello! May I ask if food values are also updated to parity in the next release? I planned to open another PR for it but if that's the case then I won't. Thank you!
Hi @Zifiv, sorry if I'm disturbing you, but it think it would be nice to have a confirmation about this.
In addition, I noticed that my bush_crop model update had an error, and that I would like to correct it by sending it here. Thank you for your time!
[bush_crop.zip](https://github.com/newhoryzon/farmers-delight-fabric/files/9549848/bush_crop.zip)

**Comment by Zifiv** [comment]
> Hello! May I ask if food values are also updated to parity in the next release? I planned to open another PR for it but if that's the case then I won't. Thank you!

Hello @blu3potato, I've synchronized the food values to the last commit of original farmer's delight while the 1.3.0 has been release, so normaly it's already updated.

I will make a check for the code of original forge mod (for the parity) in the next release (like I do in every release).

**Pull request closed without merging**
